### ISSUE TITLE
V košíku není možnost změnit měnu na USD.

### ISSUE THREAD

**Issue by TomBrousil** [LastStar/bct#10]
S tím asi souvisí, když chce zákazník zaplatit a vytvořit nový účet, při volbě preferované měny to píše "Incomplete response received from application"
![snimek obrazovky 2015-03-11 v 13 54 39](https://cloud.githubusercontent.com/assets/757795/6596781/da2e688e-c7f7-11e4-9d86-0ac1bc7ec8e3.png)
![snimek obrazovky 2015-03-11 v 13 55 49](https://cloud.githubusercontent.com/assets/757795/6596782/ddd47104-c7f7-11e4-849a-b53c38fe8244.png)

**Comment by pepe** [comment]
To jste chtěli dát pryč, možnost platit jen EUR a CZK. Můžu najít komunikaci, kde se to řešilo. Ale opravdu ten dolar chybně zůstal v profilu a při vytváření nového zákazníka. I tam je to teď odstraněno.
