### ISSUE TITLE
Publikování fontu

### ISSUE THREAD

**Issue by TomBrousil** [LastStar/bct#11]
![Uploading Screen Shot 2015-03-11 at 17.39.21.png . . .]()
- Když se dá publikovat nový font a uloží se, hlásí "Internal Server Error". Potom celé stránky BC jsou "Incomplete response received from application".
- V preview vpravo pod anotací ukazuje nenahraný obrázek, i když tam žádný být nemá. Stejně tak v About.
- V About (CV autorů) se stále neobjevuje obrázek Krause, je tam místo něj otazník.

![snimek obrazovky 2015-03-11 v 17 02 51](https://cloud.githubusercontent.com/assets/757795/6600647/1ef0ebfe-c811-11e4-8adb-adf8aef40849.png)
![snimek obrazovky 2015-03-11 v 17 03 00](https://cloud.githubusercontent.com/assets/757795/6600648/22684d2c-c811-11e4-9300-71763c33462c.png)

**Comment by pepe** [comment]
To je věc, že font kvůli správnému řazení má položku position, která prozatím nejde editovat. Řešil jsem to s @petradocekalova, když se font dělal na Betě. Musím dodělat do adminu tu položku a automatické přerovnání. Viz #13

**Comment by pepe** [comment]
tady ještě bude potřeba abyste udělali obrázek s odznakem New. Na SCT je to takové to "zubaté" kolečko.

**Comment by pepe** [comment]
Tak jsem to opravil a opravenou DB přehrál beta DB. Na betě jsem také publikoval mikser a vše se zdá v pořádku. Až budu mít new badge tak ho nahraji na server a může se font publikovat.

**Comment by TomBrousil** [comment]
Bezva, děkuju, ten obrázek je v příloze. Dej mi, prosím, vědět až to bude.

To
1. 3. 2015 v 14:59, Josef Pospíšil notifications@github.com:

**Comment by TomBrousil** [comment]
![images-new_badge](https://cloud.githubusercontent.com/assets/757795/6625458/75ae2918-c8f0-11e4-99a9-e9136008591d.gif)

**Comment by pepe** [comment]
Udělám to zítra jako první věc.

**Comment by pepe** [comment]
Je hotovo na beta. možno vidět v akci. Na www nutno publikovat font.

**Comment by TomBrousil** [comment]
Díky.
