### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by TomBrousil** [LastStar/bct#6]
Po vytvoření nového účtu někdy hodí 502 a na stránky BC se už nejde dostat. Po vyčištění cache opět funguje.

**Comment by pepe** [comment]
Našel jsem pravděpodobnou příčinu. Hlavní bylo, že si člověk musí vytvářet nový účet při vytváření objednávky. Prosím o kontrolu u vás, zda funguje.

**Comment by TomBrousil** [comment]
Zdá se, že to funguje. Zákazníci to prověří.
