### ISSUE TITLE
Admin: správa neověřených objednávek nelze vymazat.

### ISSUE THREAD

**Issue by TomBrousil** [LastStar/bct#9]
Místo buttonu Delete je PDF.
![snimek obrazovky 2015-03-11 v 0 18 33](https://cloud.githubusercontent.com/assets/757795/6593435/0662c568-c7d9-11e4-9d2c-a24e368e70c9.png)

**Comment by pepe** [comment]
Nasazena verze s opravou. Prosím o kontrolu.
